[workspace]
resolver = "2"
members = ["crates/proto", "bin/plugin", "bin/cli"]
default-members = ["crates/proto", "bin/cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
warpify-proto = { path = "crates/proto" }

[profile.release]
opt-level = "s"
lto = true
strip = true

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
